platformName: Android
#模拟器
platformVersion: 6.0.1
deviceName: 127.0.0.1:5555

#真机（真机和模拟器同时存在是，真机一定要有udid）
#platformVersion: 5.1.1
#udid: e6nvnkdan
#deviceName: MX4

appName: kaoyan3.1.0.apk
noReset: False
unicodeKeyboard: True
resetKeyboard: True

appPackage: com.tal.kaoyan
appActivity: com.tal.kaoyan.ui.activity.SplashActivity
ip: 127.0.0.1
port: 4723

